image: node:lts-alpine

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - yarn intsall
  - yarn run build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - yarn install
  - yarn run build
  artifacts:
    paths:
    - build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
